#!/bin/sh
# Generated by diffgraph — provides token to git via GIT_ASKPASS.
# Git calls this script with a prompt ("Username for..." / "Password for...")
# and reads the response from stdout.
echo '{{ token }}'
