#!/bin/sh
# Generated by diffgraph — provides username/password to git via GIT_ASKPASS.
case "$1" in
  Username*|username*) echo '{{ username }}' ;;
  Password*|password*) echo '{{ password }}' ;;
  *) echo '{{ password }}' ;;
esac
